[package]
name = "dbt2-post-process"
version = "0.1.0"
authors = ["Eli Flanagan <eli@typedspace.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
